name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write # Required to create a release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # For Arm based macs (M1 and above). Use macos-14 for Intel based macs.
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # For Intel based macs. Use macos-14 for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm' # Set this to npm, yarn or pnpm. Adjust if you use a different package manager.

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: npm install # !!! Important: Change this to 'npm install' or 'pnpm install' if you use npm or pnpm respectively !!!

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          packageManager: npm # Explicitly tell the action to use npm
          # buildCommand: 'npm run build' # Optional: Uncomment and adjust if your build script is different
          tagName: app-v__VERSION__ # The action automatically replaces __VERSION__ with the app version from tauri.conf.json
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true # Creates a draft release. Set to false to publish immediately.
          prerelease: false
          args: ${{ matrix.args }} 